"""empty message

Revision ID: bcdb45108af1
Revises: d0351d76b68c
Create Date: 2018-02-10 13:17:33.119291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcdb45108af1'
down_revision = 'd0351d76b68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'real_avatar')
    # ### end Alembic commands ###
